[package]
name = "password-gen"
version = "0.1.0"
author = "Josha Sea"
edition = "2021"
description = "A command-line tool for generating a random password"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"